lastupdatecheck: 0
recentrepos:
- /home/dupp/GIT/SPINE/Spine
- /home/dupp/GIT/SPINE/Infrastructure
- /home/dupp/GIT/IWLS/Infrastructure
startuppopupversion: 5
customcommandshistory: []
hidecommandlog: false
